config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get '/about' => 'about#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show]
    resources :sales, only: [:index, :new]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: ENV['username'], password: ENV['password']

  def show
    @categories = Category.all
    @products = Product.all 
  end

end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>
<table class="table table-bordered table-dark"
  <thead>
    <tr>
      <th scope="col">Number of Products</th>
      <th scope="col">Number of Categories</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= @products.length %> 
      </td>
      <td>
        <%= @categories.length %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to "To Admin Products Index", admin_products_path(@products), class: 'btn btn-lg btn-primary' %>